### ISSUE TITLE
App immediately closes upon attempting login

### ISSUE THREAD

**Issue by Jambopaul** [Ombrelin/plex-rich-presence#100]
I am unable to use the app because every time I try to put in my login information, the app completely closes. It even disappears from my system tray within a few seconds. Additionally, attempting to login through a browser doesn't work for me either. It just results in an endlessly loading page.

**Comment by Ombrelin** [comment]
Hello, thank you for your feedback,
Could you post your logs ? They can be found on the \`.plexrichpresence\` folder in your user directory.

**Comment by DuckersMcQuack** [comment]
Same issue here. 

2024-05-31 22:59:34.258 +02:00 [FTL] Application crashed
System.Net.Http.HttpRequestException: The requested name is valid, but no data of the requested type was found. (secure.gravatar.com:443)
 ---> System.Net.Sockets.SocketException (11004): The requested name is valid, but no data of the requested type was found.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at PlexRichPresence.UI.Avalonia.Views.ServersPage.<>c__DisplayClass0_0.<<-ctor>b__0>d.MoveNext() in D:\a\plex-rich-presence\plex-rich-presence\src\PlexRichPresence.UI.Avalonia\Views\ServersPage.axaml.cs:line 23
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run() in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 181
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 263
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 210
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at PlexRichPresence.UI.Avalonia.Program.Main(String[] args) in D:\a\plex-rich-presence\plex-rich-presence\src\PlexRichPresence.UI.Avalonia\Program.cs:line 19

**Comment by KristapsD** [comment]
For anyone having this issue:
For me deleting the following folder on windows worked - C:\Users\xxx\AppData\Roaming\PlexRichPresence\SecretCache

It does obviously ask you to re-authenticate.

**Comment by DuckersMcQuack** [comment]
> For anyone having this issue: For me deleting the following folder on windows worked - C:\Users\xxx\AppData\Roaming\PlexRichPresence\SecretCache
> 
> It does obviously ask you to re-authenticate.

Doesn't work. It'll repeat the same issue for me when i log in through browser.

**Comment by Ombrelin** [comment]
@Jambopaul based on your logs it seems you auth session expired.
Are you user or admin account of your plex server ?
