### ISSUE TITLE
BUILD FAILURE

### ISSUE THREAD

**Issue by BreakingTV** [Ombrelin/plex-rich-presence#16]
every time I start this project this error comes out:

> WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.076 s
[INFO] Finished at: 2021-01-24T18:14:49+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/home/danil/Dokumente/Programme/Other/PRP). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException

Can someone help me pls. I dont use maven and I dont know how to fix that issue!

**Comment by mclarence** [comment]
Which directory are you running the build from?

**Comment by Ombrelin** [comment]
And what are you trying to achieve ?

**Comment by BreakingTV** [comment]
I run the command in: /home/danil/Dokumente/Programme/Other/PRP

And I want to buid the programm 

distro: Linux

**Comment by mclarence** [comment]
Post the output of `ls /home/danil/Dokumente/Programme/Other/PRP` here. (or if you don't know how to do that, just open the folder in a file explorer and post the screenshot here.)

**Comment by BreakingTV** [comment]
`BOOT-INF  META-INF  org  plex-rich-presence-1.2.jar`

**Comment by mclarence** [comment]
These are not the correct files for building the program. Read below.

I'm not to sure where you got BOOT-INF, META-INF or org but you can just run the program (no building involved) by double clicking the `plex-rich-presence-1.2.jar` file or run `java -jar plex-rich-presence-1.2.jar` in a terminal.

If you want to build the program you must clone this repository with git or download the zip file of the source code from github, `cd` into the cloned repo directory (where pom.xml) is located and run `mvn clean package` to build the program.

**Comment by BreakingTV** [comment]
When I it this error comes out:

> Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:92)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at fr.arsenelapostolet.plexrichpresence.PlexRichPresenceApplication.main(PlexRichPresenceApplication.java:10)
        ... 8 more
Caused by: java.lang.ClassNotFoundException: javafx.application.Application
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:92)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 20 more

I used: `java -jar plex-rich-presence-1.2.jar` and `sudo java -jar plex-rich-presence-1.2.jar`

**Comment by mclarence** [comment]
Must use Java 8. Please check if you have java 8 installed.
