### ISSUE TITLE
"Error getting sessions"

### ISSUE THREAD

**Issue by MightyTea** [Ombrelin/plex-rich-presence#33]
![image](https://user-images.githubusercontent.com/32665892/109416025-29fa1580-79bc-11eb-8014-839b85933ac7.png)

**Comment by Mightyyt** [comment]
@mclarence @Ombrelin any idea?

**Comment by Ombrelin** [comment]
Hello,
Are you the admin of the server and does you Plex account references server that are not active anymore ?

**Comment by Mightyyt** [comment]
Yes, It references server that aren't active no more

**Comment by Mightyyt** [comment]
![image](https://user-images.githubusercontent.com/32665892/109430133-f8a33900-79ff-11eb-9047-60f33211c0e9.png)
but i deleted everything and it doesn't change anything

**Comment by Mightyyt** [comment]
@Ombrelin any idea?

**Comment by mclarence** [comment]
Please download the latest .jar file instead of the windows/exe one and run the following in cmd:

`"C:\Program Files (x86)\Plex Rich Presence\jre\bin\java.exe" -jar <path to downloaded jar file> -Dlogging.level.root=DEBUG` and post the output from cmd here.

**Comment by Mightyyt** [comment]
well, now it works but the presence isn't working, like it gives me 0 errors but presence doesn't shows up on discord @mclarence

**Comment by mclarence** [comment]
It wont show anything if nothing is playing in plex.

If you are still having issues, please follow my latest comment.

**Comment by Mightyyt** [comment]
```
00:02:12.942 [RxIoScheduler-2] INFO  f.a.p.v.MainViewModel - Successfully logged in as: crazyball.tr@gmail.com
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
        at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:66)
        at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:40)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at com.sun.javafx.tk.quantum.GlassWindowEventHandler.lambda$handleWindowEvent$4(GlassWindowEventHandler.java:176)
        at com.sun.javafx.tk.quantum.GlassWindowEventHandler$$Lambda$472/0x0000000000000000.get(Unknown Source)
        at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:390)
        at com.sun.javafx.tk.quantum.GlassWindowEventHandler.handleWindowEvent(GlassWindowEventHandler.java:174)
        at com.sun.glass.ui.Window.handleWindowEvent(Window.java:1346)
        at com.sun.glass.ui.Window.notifyResize(Window.java:1305)
        at com.sun.glass.ui.win.WinWindow.notifyResize(WinWindow.java:236)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
        at com.sun.glass.ui.win.WinApplication$$Lambda$65/0x0000000000000000.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

``` @mclarence

**Comment by mclarence** [comment]
You need to post the full debug log. This error is related to the GUI.

**Comment by Mightyyt** [comment]
> You need to post the full debug log. This error is related to the GUI.

It contains my IP address homie, i'm trusting you but not whoever watching this thread

**Comment by mclarence** [comment]
Send it to me on my discord mclarence#0736

**Comment by mclarence** [comment]
Please download the new version released and manually specify your plex server in the settings.

Let me know how it goes.

**Comment by AaronWiora** [comment]
I'm getting the same issue but I'm not sure if my configuration is correct. I had to use manual config because the automatic one will lead to another error. Which port do I have to use? Tried 80 & 443

**Comment by Ombrelin** [comment]
PLEX Media Server usuall TCP port is 32400
