### ISSUE TITLE
Unable to disconnect 

### ISSUE THREAD

**Issue by majora2007** [Ombrelin/plex-rich-presence#76]
On v2.0.1-beta, I signed up. After logging in via browser, the application crashed due to a timeout. I relaunched to disconnect and attempt to use a custom setup, but disconnect is disabled.

Expected: 
To be able to disconnect at any time

```
2022-10-09 11:26:15.388 -05:00 [INF] Listening to sessions via polling for IP : redacted for User : majora2007
2022-10-09 11:26:36.442 -05:00 [FTL] Application crashed
System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (redacted:32400)
 ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
```

**Comment by Ombrelin** [comment]
Thank you for your feedback, this error shouldn't crash the app. I'll introduce a fix for that has well as debug the issue with the disconnect button.
In the meantime, you can wipe the `storedData.json` file next to the log file, it will reset the config of the app.

**Comment by majora2007** [comment]
Awesome, thanks for responding so quickly. Looking forward to the full v2.0 as 1.0 was a bit laggy, but is awesome when it works. I'll leave the issue in case you want to close against the issue.
