### ISSUE TITLE
2.0 crashes when playing movie

### ISSUE THREAD

**Issue by jakemoritz** [Ombrelin/plex-rich-presence#78]
I installed the 2.01-beta version when watching a movie, and it crashed upon launch. I am using Windows 10. Here are the logs, and I've removed any nonrelevant info:

```
2022-10-09 17:43:43.020 -04:00 [INF] Listening to sessions via polling for IP : <IP> for User : <Plex_User>
2022-10-09 17:43:43.202 -04:00 [INF] StatusCode: OK. Request Uri: http://<IP>:<port>/status/sessions?includeExternalMedia=1&includePreferences=1&includeExtras=1&includeStations=1&includeChapters=1&includeGuids=1&X-Plex-Client-Identifier=<id>
2022-10-09 17:43:43.203 -04:00 [INF] 
{
  "MediaContainer": {
    "size": 2,
    "Metadata": [
      {
        "rating": 8.5
      }
    ]
  }
}
2022-10-09 17:43:43.251 -04:00 [FTL] Application crashed
System.Text.Json.JsonException: The JSON value could not be converted to System.String. Path: $.MediaContainer.Metadata[0].rating | LineNumber: 0 | BytePositionInLine: 530.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'Number' as a string.
   at System.Text.Json.Utf8JsonReader.GetString()
   at System.Text.Json.Serialization.Converters.StringConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Plex.ServerApi.Api.ApiService.DeserialiseResponse[T](HttpResponseMessage httpResponse, String contentResponse)
   at Plex.ServerApi.Api.ApiService.InvokeApiAsync[T](ApiRequest request)
   at Plex.ServerApi.Clients.PlexServerClient.FetchWithWrapper[T](String baseUrl, String endpoint, String authToken, HttpMethod method, Dictionary`2 queryParams)
   at Plex.ServerApi.Clients.PlexServerClient.GetSessionsAsync(String authToken, String plexServerHost)
   at PlexRichPresence.PlexActivity.PlexSessionsPollingStrategy.GetSessions(String username, String serverIp, Int32 serverPort, String userToken)+MoveNext() in D:\a\plex-rich-presence\plex-rich-presence\src\PlexRichPresence.PlexActivity\PlexSessionsPollingStrategy.cs:line 30
   at PlexRichPresence.PlexActivity.PlexSessionsPollingStrategy.GetSessions(String username, String serverIp, Int32 serverPort, String userToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at PlexRichPresence.ViewModels.PlexActivityPageViewModel.StartActivity() in D:\a\plex-rich-presence\plex-rich-presence\src\PlexRichPresence.ViewModels\PlexActivityPageViewModel.cs:line 50
   at PlexRichPresence.ViewModels.PlexActivityPageViewModel.StartActivity() in D:\a\plex-rich-presence\plex-rich-presence\src\PlexRichPresence.ViewModels\PlexActivityPageViewModel.cs:line 50
   at PlexRichPresence.UI.Avalonia.Views.ActivityPage.<>c__DisplayClass0_0.<<-ctor>b__0>d.MoveNext() in D:\a\plex-rich-presence\plex-rich-presence\src\PlexRichPresence.UI.Avalonia\Views\ActivityPage.axaml.cs:line 18
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run() in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 181
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 263
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 210
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at PlexRichPresence.UI.Avalonia.Program.Main(String[] args) in D:\a\plex-rich-presence\plex-rich-presence\src\PlexRichPresence.UI.Avalonia\Program.cs:line 19
```

**Comment by Ombrelin** [comment]
Thanks you for your feedback, and for the logs which are quite insightful. I see the problem, and it's due to the plex client lib which I use having outdated schema. I'll contribute fix to them in order to fix this issue.

**Comment by Ombrelin** [comment]
Just submitted PR to the lib if you want to check progress of merge by the maintainer : https://github.com/jensenkd/plex-api/pull/88

**Comment by Ombrelin** [comment]
Should be fixed in last release, please re-open if still having this issue
