### ISSUE TITLE
Can't reach server

### ISSUE THREAD

**Issue by JihadiJackass** [Ombrelin/plex-rich-presence#92]
![image](https://user-images.githubusercontent.com/11571144/215883488-d61c1c50-84c0-4a78-8ca6-ddfab49ad0c4.png)

Not sure what to do or why this is happening.

![image](https://user-images.githubusercontent.com/11571144/215884051-f806aa27-f5b9-4907-938b-a2b86198dee7.png)

This is the logs2023013116.txt, I am not pasting it directly as there is a lot of private info in there. It just loops these exact lines of code, so not like I need to.

**Comment by Greshapa** [comment]
I had an issue similar to this. After a server reboot, PRP kept telling me that it couldn't reach the server, and the IP address was changed to public (Instead of my proper local IP)

Can't confirm that this will fix your issue but heres what I did:
1.) Change server and re-enter new data (Server IP and Port) and **enabled** both Use Custom Server and Is Custom Server Owned
2.) Log all the way out of the app
3.) Exit the app
3.) Re-open and log all the way back into the app
And from here on i havn't got the ' can't reach server ' error anymore.

Best of luck

**Comment by hax4dazy** [comment]
I was also having this issue, turns out that the [plex default port is 32400](https://support.plex.tv/articles/201543147-what-network-ports-do-i-need-to-allow-through-my-firewall/) instead of what the program defaults to. This causes the connection to fail every time while selecting a server. I had to manually change the port in the config file which is stored in `%userprofile%/.plexrichpresence`. Would be nice if this was fixed or give us the option to change the port without having to configure our own server

**Comment by Ombrelin** [comment]
I'm not sure I understand the use causing this issue, and I'm not sure how to reproduce it.
I would need to portion of the log which contains "Could not connect to server" message

**Comment by hax4dazy** [comment]
> I'm not sure I understand the use causing this issue
The issue for me was that the client was trying to reach the server on a port which wasn't used. Either somehow Plex gave it the wrong port number or the app attempted to connect to the server while using the wrong port.

**Comment by Ombrelin** [comment]
Ha, I think I have an idea, since I don't have a default port setup in the app, my guess is that if you used a server present on your PLEX account, its port wasn't up to date.

**Comment by hax4dazy** [comment]
Maybe? I'm not sure why it choose that port because my plex port on my network has always been the recommended default one. Once I changed that in PRC's config file it fully connected to my server

**Comment by Ombrelin** [comment]
I advise you to check the PLEX servers paired which are paired with your PLEX account. The data used when using auotmatic configuration comes from your PLEX account, through PLEX's API. I don't control this data.

**Comment by hax4dazy** [comment]
Hmm that is strange yeah. Plex is reporting that the outside the world is connecting to plex through that port while that port isn't even enabled. I just fixed this by specifying plex to use the _correct_ port instead of the one it was using before. Thanks for your support ❤️

**Comment by sambilbow** [comment]
Hi, I've installed the `.deb` manually on Arch Linux and am receiving this error: "Can't reach server !", both when connecting automatically and manually.

```
2023-07-18 10:31:36.891 +01:00 [INF] StatusCode: OK. Request Uri: https://plex.tv/api/v2/user.json/
2023-07-18 10:31:36.891 +01:00 [INF] {<a bunch of confidential stuff>}
2023-07-18 10:31:44.982 +01:00 [INF] Listening to sessions via polling for user : sambilbow
```

and then

```
2023-07-18 10:31:45.007 +01:00 [ERR] Could not connect to server
System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The response ended prematurely.
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Plex.ServerApi.Api.PlexRequestsHttpClient.SendAsync(HttpRequestMessage request)
   at Plex.ServerApi.Api.ApiService.InvokeApiAsync[T](ApiRequest request)
   at Plex.ServerApi.Clients.PlexServerClient.FetchWithWrapper[T](String baseUrl, String endpoint, String authToken, HttpMethod method, Dictionary`2 queryParams)
   at Plex.ServerApi.Clients.PlexServerClient.GetSessionsAsync(String authToken, String plexServerHost)
   at PlexRichPresence.PlexActivity.PlexSessionsPollingStrategy.GetSessions(String username, String serverIp, Int32 serverPort, String userToken)+MoveNext() in /__w/plex-rich-presence/plex-rich-presence/src/PlexRichPresence.PlexActivity/PlexSessionsPollingStrategy.cs:line 34
   at PlexRichPresence.PlexActiv2023-07-18 10:31:36.891 +01:00 [INF] StatusCode: OK. Request Uri: https://plex.tv/api/v2/user.json/ity.PlexSessionsPollingStrategy.GetSessions(String username, String serverIp, Int32 serverPort, String userToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at PlexRichPresence.ViewModels.PlexActivityPageViewModel.StartActivity() in /__w/plex-rich-presence/plex-rich-presence/src/PlexRichPresence.ViewModels/PlexActivityPageViewModel.cs:line 75
   at PlexRichPresence.ViewModels.PlexActivityPageViewModel.StartActivity() in /__w/plex-rich-presence/plex-rich-presence/src/PlexRichPresence.ViewModels/PlexActivityPageViewModel.cs:line 75
```

The IP and port match the ones found in Plex > Settings > Remote Access (i.e. my global IP)
