### ISSUE TITLE
App crashes directly upon opening it

### ISSUE THREAD

**Issue by hax4dazy** [Ombrelin/plex-rich-presence#94]
The app starts and then instantly closes itself. I was trying to fix #92 this issue but now I can't use the app at all. Trying to reinstall it does nothing

I'm using windows 10 with the latest version downloaded directly from GitHub

**Comment by Ombrelin** [comment]
Hi, thank you for reporting, could you update you logs ? (Can be found under <your user directory>/.plexrichpresence)

**Comment by hax4dazy** [comment]
Yeah sure, here you go 
```
2023-02-21 00:13:46.054 +01:00 [FTL] Application crashed
System.Collections.Generic.KeyNotFoundException: The given key 'plex_token' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at PlexRichPresence.UI.Avalonia.Services.StorageService.GetAsync(String key) in D:\a\plex-rich-presence\plex-rich-presence\src\PlexRichPresence.UI.Avalonia\Services\StorageService.cs:line 78
   at PlexRichPresence.ViewModels.PlexActivityPageViewModel.InitStrategy() in D:\a\plex-rich-presence\plex-rich-presence\src\PlexRichPresence.ViewModels\PlexActivityPageViewModel.cs:line 47
   at PlexRichPresence.UI.Avalonia.Views.ActivityPage.<>c__DisplayClass0_0.<<-ctor>b__0>d.MoveNext() in D:\a\plex-rich-presence\plex-rich-presence\src\PlexRichPresence.UI.Avalonia\Views\ActivityPage.axaml.cs:line 17
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run() in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 181
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 263
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 210
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at PlexRichPresence.UI.Avalonia.Program.Main(String[] args) in D:\a\plex-rich-presence\plex-rich-presence\src\PlexRichPresence.UI.Avalonia\Program.cs:line 19
```

**Comment by hax4dazy** [comment]
I would have found this earlier but I was looking in `%appdata%` and `%localuserdata%` instead of the user folder

**Comment by hax4dazy** [comment]
I tried using the normal login instead of the browser one but this app does not support 2FA so it just crashes with this error message 
```
2023-02-21 21:54:16.375 +01:00 [INF] StatusCode: Unauthorized. Request Uri: https://plex.tv/users/sign_in.json/
2023-02-21 21:54:16.418 +01:00 [FTL] Application crashed
System.ApplicationException: Unsuccessful response from 3rd Party API
   at Plex.ServerApi.Api.ApiService.LogApiUnsuccessfulAsync(ApiRequest request, HttpResponseMessage httpResponse)
   at Plex.ServerApi.Api.ApiService.InvokeApiAsync[T](ApiRequest request)
   at Plex.ServerApi.Clients.PlexAccountClient.SignInAsync(String username, String password)
   at Plex.ServerApi.Clients.PlexAccountClient.GetPlexAccountAsync(String username, String password)
   at PlexRichPresence.ViewModels.LoginPageViewModel.LoginWithCredentials() in D:\a\plex-rich-presence\plex-rich-presence\src\PlexRichPresence.ViewModels\LoginPageViewModel.cs:line 38
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 283
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 210
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at PlexRichPresence.UI.Avalonia.Program.Main(String[] args) in D:\a\plex-rich-presence\plex-rich-presence\src\PlexRichPresence.UI.Avalonia\Program.cs:line 19
```

**Comment by Ombrelin** [comment]
Mmmh, that's strange, you should not get to the activity page without having a token populated.
Did you modify the `storedData.json` file manually ?

**Comment by Ombrelin** [comment]
I'll introduce a fallback mechanism to show the login screen when it happens.

**Comment by hax4dazy** [comment]
> Mmmh, that's strange, you should not get to the activity page without having a token populated.
> Did you modify the storedData.json file manually ?

Nope, I haven't modified the file `storedData.json` myself outside of changing the IP address / port number

**Comment by Ombrelin** [comment]
Fix implemented in last release
